server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.myproducer
      routing-key:
        producer: rk.producer.myproducer
      deadletter:
        producer: dl.producer.myproducer